
package com.jubaozan.service.promotion.model;

import java.time.LocalDateTime;

/**
 * 报名表单选择题选项(PROMOTION_CUSTOMER_ANSWER)
 * 
 * @author fuzhuan
 * @version 1.0.0 2019-09-21
 */
public class PromotionCustomerAnswerEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3482882636578526676L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** 客户编号 */
    private Integer customerNo;

    /** 表单ID */
    private Long formId;

    /** 问题ID*/
    private Long questionId;

    /** 答案 */
    private String answer;

    /** sjid */
    private Integer sjid;

    /** createTime */
    private LocalDateTime createTime;

    public PromotionCustomerAnswerEntity() {
    }


    public Long getId() {
        return this.id;
    }

    public Integer getCustomerNo() {
        return this.customerNo;
    }

    public Long getFormId() {
        return this.formId;
    }

    public Long getQuestionId() {
        return this.questionId;
    }

    public String getAnswer() {
        return this.answer;
    }

    public Integer getSjid() {
        return this.sjid;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setCustomerNo(Integer customerNo) {
        this.customerNo = customerNo;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public void setSjid(Integer sjid) {
        this.sjid = sjid;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof PromotionCustomerAnswerEntity)) return false;
        final PromotionCustomerAnswerEntity other = (PromotionCustomerAnswerEntity) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final Object this$customerNo = this.getCustomerNo();
        final Object other$customerNo = other.getCustomerNo();
        if (this$customerNo == null ? other$customerNo != null : !this$customerNo.equals(other$customerNo))
            return false;
        final Object this$formId = this.getFormId();
        final Object other$formId = other.getFormId();
        if (this$formId == null ? other$formId != null : !this$formId.equals(other$formId)) return false;
        final Object this$questionId = this.getQuestionId();
        final Object other$questionId = other.getQuestionId();
        if (this$questionId == null ? other$questionId != null : !this$questionId.equals(other$questionId))
            return false;
        final Object this$answer = this.getAnswer();
        final Object other$answer = other.getAnswer();
        if (this$answer == null ? other$answer != null : !this$answer.equals(other$answer)) return false;
        final Object this$sjid = this.getSjid();
        final Object other$sjid = other.getSjid();
        if (this$sjid == null ? other$sjid != null : !this$sjid.equals(other$sjid)) return false;
        final Object this$createTime = this.getCreateTime();
        final Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime))
            return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof PromotionCustomerAnswerEntity;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $customerNo = this.getCustomerNo();
        result = result * PRIME + ($customerNo == null ? 43 : $customerNo.hashCode());
        final Object $formId = this.getFormId();
        result = result * PRIME + ($formId == null ? 43 : $formId.hashCode());
        final Object $questionId = this.getQuestionId();
        result = result * PRIME + ($questionId == null ? 43 : $questionId.hashCode());
        final Object $answer = this.getAnswer();
        result = result * PRIME + ($answer == null ? 43 : $answer.hashCode());
        final Object $sjid = this.getSjid();
        result = result * PRIME + ($sjid == null ? 43 : $sjid.hashCode());
        final Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        return result;
    }

    public String toString() {
        return "PromotionCustomerAnswerEntity(id=" + this.getId() + ", customerNo=" + this.getCustomerNo() + ", formId=" + this.getFormId() + ", questionId=" + this.getQuestionId() + ", answer=" + this.getAnswer() + ", sjid=" + this.getSjid() + ", createTime=" + this.getCreateTime() + ")";
    }
}