
package com.jubaozan.service.promotion.model;

import java.time.LocalDateTime;

/**
 * 报名表单基本信息(PROMOTION_ENROLL_FORM)
 * 
 * @author fuzhuan
 * @version 1.0.0 2019-09-21
 */
public class PromotionEnrollFormEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -4493001394790680271L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** 标题 */
    private String title;

    /** 内容描述 */
    private String description;

    /** 开始时间 */
    private LocalDateTime startTime;

    /** 结束时间 */
    private LocalDateTime endTime;

    /** 跳转地址 */
    private String jumpUrl;

    /** -1 停用 0 未启用  1 进行中 */
    private Integer status;

    /** 顶部图片地址 */
    private String imageTop;

    /** 底部图片地址 */
    private String imageBottom;

    /** sjid */
    private Integer sjid;

    /** createTime */
    private LocalDateTime createTime;

    /** updateTime */
    private LocalDateTime updateTime;

    public PromotionEnrollFormEntity() {
    }


    public Long getId() {
        return this.id;
    }

    public String getTitle() {
        return this.title;
    }

    public String getDescription() {
        return this.description;
    }

    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    public String getJumpUrl() {
        return this.jumpUrl;
    }

    public Integer getStatus() {
        return this.status;
    }

    public String getImageTop() {
        return this.imageTop;
    }

    public String getImageBottom() {
        return this.imageBottom;
    }

    public Integer getSjid() {
        return this.sjid;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public void setImageTop(String imageTop) {
        this.imageTop = imageTop;
    }

    public void setImageBottom(String imageBottom) {
        this.imageBottom = imageBottom;
    }

    public void setSjid(Integer sjid) {
        this.sjid = sjid;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof PromotionEnrollFormEntity)) return false;
        final PromotionEnrollFormEntity other = (PromotionEnrollFormEntity) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final Object this$title = this.getTitle();
        final Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final Object this$description = this.getDescription();
        final Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description))
            return false;
        final Object this$startTime = this.getStartTime();
        final Object other$startTime = other.getStartTime();
        if (this$startTime == null ? other$startTime != null : !this$startTime.equals(other$startTime)) return false;
        final Object this$endTime = this.getEndTime();
        final Object other$endTime = other.getEndTime();
        if (this$endTime == null ? other$endTime != null : !this$endTime.equals(other$endTime)) return false;
        final Object this$jumpUrl = this.getJumpUrl();
        final Object other$jumpUrl = other.getJumpUrl();
        if (this$jumpUrl == null ? other$jumpUrl != null : !this$jumpUrl.equals(other$jumpUrl)) return false;
        final Object this$status = this.getStatus();
        final Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final Object this$imageTop = this.getImageTop();
        final Object other$imageTop = other.getImageTop();
        if (this$imageTop == null ? other$imageTop != null : !this$imageTop.equals(other$imageTop)) return false;
        final Object this$imageBottom = this.getImageBottom();
        final Object other$imageBottom = other.getImageBottom();
        if (this$imageBottom == null ? other$imageBottom != null : !this$imageBottom.equals(other$imageBottom))
            return false;
        final Object this$sjid = this.getSjid();
        final Object other$sjid = other.getSjid();
        if (this$sjid == null ? other$sjid != null : !this$sjid.equals(other$sjid)) return false;
        final Object this$createTime = this.getCreateTime();
        final Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime))
            return false;
        final Object this$updateTime = this.getUpdateTime();
        final Object other$updateTime = other.getUpdateTime();
        if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime))
            return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof PromotionEnrollFormEntity;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final Object $startTime = this.getStartTime();
        result = result * PRIME + ($startTime == null ? 43 : $startTime.hashCode());
        final Object $endTime = this.getEndTime();
        result = result * PRIME + ($endTime == null ? 43 : $endTime.hashCode());
        final Object $jumpUrl = this.getJumpUrl();
        result = result * PRIME + ($jumpUrl == null ? 43 : $jumpUrl.hashCode());
        final Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final Object $imageTop = this.getImageTop();
        result = result * PRIME + ($imageTop == null ? 43 : $imageTop.hashCode());
        final Object $imageBottom = this.getImageBottom();
        result = result * PRIME + ($imageBottom == null ? 43 : $imageBottom.hashCode());
        final Object $sjid = this.getSjid();
        result = result * PRIME + ($sjid == null ? 43 : $sjid.hashCode());
        final Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        final Object $updateTime = this.getUpdateTime();
        result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
        return result;
    }

    public String toString() {
        return "PromotionEnrollFormEntity(id=" + this.getId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", startTime=" + this.getStartTime() + ", endTime=" + this.getEndTime() + ", jumpUrl=" + this.getJumpUrl() + ", status=" + this.getStatus() + ", imageTop=" + this.getImageTop() + ", imageBottom=" + this.getImageBottom() + ", sjid=" + this.getSjid() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ")";
    }
}