
package com.jubaozan.service.promotion.model;

import java.time.LocalDateTime;

/**
 * 报名表单选择题选项(PROMOTION_CHOICE_OPTION)
 * 
 * @author fuzhuan
 * @version 1.0.0 2019-09-21
 */
public class PromotionChoiceOptionEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 448186389977882580L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** formId */
    private Long formId;

    /** 题目ID */
    private Long questionId;

    /** 题目选项 */
    private String choiceOption;

    /** sjid */
    private Integer sjid;

    /** createTime */
    private LocalDateTime createTime;

    /** updateTime */
    private LocalDateTime updateTime;

    public PromotionChoiceOptionEntity() {
    }


    public Long getId() {
        return this.id;
    }

    public Long getFormId() {
        return this.formId;
    }

    public Long getQuestionId() {
        return this.questionId;
    }

    public String getChoiceOption() {
        return this.choiceOption;
    }

    public Integer getSjid() {
        return this.sjid;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public void setChoiceOption(String choiceOption) {
        this.choiceOption = choiceOption;
    }

    public void setSjid(Integer sjid) {
        this.sjid = sjid;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof PromotionChoiceOptionEntity)) return false;
        final PromotionChoiceOptionEntity other = (PromotionChoiceOptionEntity) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final Object this$formId = this.getFormId();
        final Object other$formId = other.getFormId();
        if (this$formId == null ? other$formId != null : !this$formId.equals(other$formId)) return false;
        final Object this$questionId = this.getQuestionId();
        final Object other$questionId = other.getQuestionId();
        if (this$questionId == null ? other$questionId != null : !this$questionId.equals(other$questionId))
            return false;
        final Object this$choiceOption = this.getChoiceOption();
        final Object other$choiceOption = other.getChoiceOption();
        if (this$choiceOption == null ? other$choiceOption != null : !this$choiceOption.equals(other$choiceOption))
            return false;
        final Object this$sjid = this.getSjid();
        final Object other$sjid = other.getSjid();
        if (this$sjid == null ? other$sjid != null : !this$sjid.equals(other$sjid)) return false;
        final Object this$createTime = this.getCreateTime();
        final Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime))
            return false;
        final Object this$updateTime = this.getUpdateTime();
        final Object other$updateTime = other.getUpdateTime();
        if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime))
            return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof PromotionChoiceOptionEntity;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $formId = this.getFormId();
        result = result * PRIME + ($formId == null ? 43 : $formId.hashCode());
        final Object $questionId = this.getQuestionId();
        result = result * PRIME + ($questionId == null ? 43 : $questionId.hashCode());
        final Object $choiceOption = this.getChoiceOption();
        result = result * PRIME + ($choiceOption == null ? 43 : $choiceOption.hashCode());
        final Object $sjid = this.getSjid();
        result = result * PRIME + ($sjid == null ? 43 : $sjid.hashCode());
        final Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        final Object $updateTime = this.getUpdateTime();
        result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
        return result;
    }

    public String toString() {
        return "PromotionChoiceOptionEntity(id=" + this.getId() + ", formId=" + this.getFormId() + ", questionId=" + this.getQuestionId() + ", choiceOption=" + this.getChoiceOption() + ", sjid=" + this.getSjid() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ")";
    }
}