
package com.jubaozan.service.promotion.model;

import java.time.LocalDateTime;
import java.util.List;

/**
 * 报名表单题目(PROMOTION_FORM_QUESTION)
 * 
 * @author fuzhuan
 * @version 1.0.0 2019-09-21
 */
public class PromotionFormQuestionEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3668491979892809639L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** 表单ID */
    private Long formId;

    /** 题目类型 */
    private Integer questionType;

    /** 题干 */
    private String questionTitle;

    /** sjid */
    private Integer sjid;

    /** createTime */
    private LocalDateTime createTime;

    /** updateTime */
    private LocalDateTime updateTime;

    private List<PromotionChoiceOptionEntity> choiceOptionList;

    public PromotionFormQuestionEntity() {
    }

    public Long getId() {
        return this.id;
    }

    public Long getFormId() {
        return this.formId;
    }

    public Integer getQuestionType() {
        return this.questionType;
    }

    public String getQuestionTitle() {
        return this.questionTitle;
    }

    public Integer getSjid() {
        return this.sjid;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public List<PromotionChoiceOptionEntity> getChoiceOptionList() {
        return this.choiceOptionList;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle;
    }

    public void setSjid(Integer sjid) {
        this.sjid = sjid;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public void setChoiceOptionList(List<PromotionChoiceOptionEntity> choiceOptionList) {
        this.choiceOptionList = choiceOptionList;
    }

    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof PromotionFormQuestionEntity)) return false;
        final PromotionFormQuestionEntity other = (PromotionFormQuestionEntity) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final Object this$formId = this.getFormId();
        final Object other$formId = other.getFormId();
        if (this$formId == null ? other$formId != null : !this$formId.equals(other$formId)) return false;
        final Object this$questionType = this.getQuestionType();
        final Object other$questionType = other.getQuestionType();
        if (this$questionType == null ? other$questionType != null : !this$questionType.equals(other$questionType))
            return false;
        final Object this$questionTitle = this.getQuestionTitle();
        final Object other$questionTitle = other.getQuestionTitle();
        if (this$questionTitle == null ? other$questionTitle != null : !this$questionTitle.equals(other$questionTitle))
            return false;
        final Object this$sjid = this.getSjid();
        final Object other$sjid = other.getSjid();
        if (this$sjid == null ? other$sjid != null : !this$sjid.equals(other$sjid)) return false;
        final Object this$createTime = this.getCreateTime();
        final Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime))
            return false;
        final Object this$updateTime = this.getUpdateTime();
        final Object other$updateTime = other.getUpdateTime();
        if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime))
            return false;
        final Object this$choiceOptionList = this.getChoiceOptionList();
        final Object other$choiceOptionList = other.getChoiceOptionList();
        if (this$choiceOptionList == null ? other$choiceOptionList != null : !this$choiceOptionList.equals(other$choiceOptionList))
            return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof PromotionFormQuestionEntity;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $formId = this.getFormId();
        result = result * PRIME + ($formId == null ? 43 : $formId.hashCode());
        final Object $questionType = this.getQuestionType();
        result = result * PRIME + ($questionType == null ? 43 : $questionType.hashCode());
        final Object $questionTitle = this.getQuestionTitle();
        result = result * PRIME + ($questionTitle == null ? 43 : $questionTitle.hashCode());
        final Object $sjid = this.getSjid();
        result = result * PRIME + ($sjid == null ? 43 : $sjid.hashCode());
        final Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        final Object $updateTime = this.getUpdateTime();
        result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
        final Object $choiceOptionList = this.getChoiceOptionList();
        result = result * PRIME + ($choiceOptionList == null ? 43 : $choiceOptionList.hashCode());
        return result;
    }

    public String toString() {
        return "PromotionFormQuestionEntity(id=" + this.getId() + ", formId=" + this.getFormId() + ", questionType=" + this.getQuestionType() + ", questionTitle=" + this.getQuestionTitle() + ", sjid=" + this.getSjid() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", choiceOptionList=" + this.getChoiceOptionList() + ")";
    }
}