
package com.jubaozan.service.promotion.model;

import com.jubaozan.service.promotion.vo.form.EnrollCustomerAnswerVO;

import java.time.LocalDateTime;
import java.util.List;

/**
 * 表单报名客户信息表(PROMOTION_ENROLL_CUSTOMER_INFO)
 * 
 * @author fuzhuan
 * @version 1.0.0 2019-09-21
 */
public class PromotionEnrollCustomerInfoEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 705823264206862038L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** 表单ID */
    private Long formId;

    /** 客户编号 */
    private Integer customerNo;

    /** 姓名 */
    private String fullName;

    /** 手机号 */
    private String mobile;

    /** remark */
    private String remark;

    /** sjid */
    private Integer sjid;

    /** 创建时间 */
    private LocalDateTime createTime;

    /** 更新时间 */
    private LocalDateTime updateTime;

    /** 客户答案集合 */
    private List<PromotionCustomerAnswerEntity> answerEntityList;

    private List<EnrollCustomerAnswerVO> questionList;

    public PromotionEnrollCustomerInfoEntity() {
    }

    public Long getId() {
        return this.id;
    }

    public Long getFormId() {
        return this.formId;
    }

    public Integer getCustomerNo() {
        return this.customerNo;
    }

    public String getFullName() {
        return this.fullName;
    }

    public String getMobile() {
        return this.mobile;
    }

    public String getRemark() {
        return this.remark;
    }

    public Integer getSjid() {
        return this.sjid;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public List<PromotionCustomerAnswerEntity> getAnswerEntityList() {
        return this.answerEntityList;
    }

    public List<EnrollCustomerAnswerVO> getQuestionList() {
        return this.questionList;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public void setCustomerNo(Integer customerNo) {
        this.customerNo = customerNo;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setSjid(Integer sjid) {
        this.sjid = sjid;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public void setAnswerEntityList(List<PromotionCustomerAnswerEntity> answerEntityList) {
        this.answerEntityList = answerEntityList;
    }

    public void setQuestionList(List<EnrollCustomerAnswerVO> questionList) {
        this.questionList = questionList;
    }

    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof PromotionEnrollCustomerInfoEntity)) return false;
        final PromotionEnrollCustomerInfoEntity other = (PromotionEnrollCustomerInfoEntity) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final Object this$formId = this.getFormId();
        final Object other$formId = other.getFormId();
        if (this$formId == null ? other$formId != null : !this$formId.equals(other$formId)) return false;
        final Object this$customerNo = this.getCustomerNo();
        final Object other$customerNo = other.getCustomerNo();
        if (this$customerNo == null ? other$customerNo != null : !this$customerNo.equals(other$customerNo))
            return false;
        final Object this$fullName = this.getFullName();
        final Object other$fullName = other.getFullName();
        if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
        final Object this$mobile = this.getMobile();
        final Object other$mobile = other.getMobile();
        if (this$mobile == null ? other$mobile != null : !this$mobile.equals(other$mobile)) return false;
        final Object this$remark = this.getRemark();
        final Object other$remark = other.getRemark();
        if (this$remark == null ? other$remark != null : !this$remark.equals(other$remark)) return false;
        final Object this$sjid = this.getSjid();
        final Object other$sjid = other.getSjid();
        if (this$sjid == null ? other$sjid != null : !this$sjid.equals(other$sjid)) return false;
        final Object this$createTime = this.getCreateTime();
        final Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime))
            return false;
        final Object this$updateTime = this.getUpdateTime();
        final Object other$updateTime = other.getUpdateTime();
        if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime))
            return false;
        final Object this$answerEntityList = this.getAnswerEntityList();
        final Object other$answerEntityList = other.getAnswerEntityList();
        if (this$answerEntityList == null ? other$answerEntityList != null : !this$answerEntityList.equals(other$answerEntityList))
            return false;
        final Object this$questionList = this.getQuestionList();
        final Object other$questionList = other.getQuestionList();
        if (this$questionList == null ? other$questionList != null : !this$questionList.equals(other$questionList))
            return false;
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof PromotionEnrollCustomerInfoEntity;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $formId = this.getFormId();
        result = result * PRIME + ($formId == null ? 43 : $formId.hashCode());
        final Object $customerNo = this.getCustomerNo();
        result = result * PRIME + ($customerNo == null ? 43 : $customerNo.hashCode());
        final Object $fullName = this.getFullName();
        result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
        final Object $mobile = this.getMobile();
        result = result * PRIME + ($mobile == null ? 43 : $mobile.hashCode());
        final Object $remark = this.getRemark();
        result = result * PRIME + ($remark == null ? 43 : $remark.hashCode());
        final Object $sjid = this.getSjid();
        result = result * PRIME + ($sjid == null ? 43 : $sjid.hashCode());
        final Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        final Object $updateTime = this.getUpdateTime();
        result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
        final Object $answerEntityList = this.getAnswerEntityList();
        result = result * PRIME + ($answerEntityList == null ? 43 : $answerEntityList.hashCode());
        final Object $questionList = this.getQuestionList();
        result = result * PRIME + ($questionList == null ? 43 : $questionList.hashCode());
        return result;
    }

    public String toString() {
        return "PromotionEnrollCustomerInfoEntity(id=" + this.getId() + ", formId=" + this.getFormId() + ", customerNo=" + this.getCustomerNo() + ", fullName=" + this.getFullName() + ", mobile=" + this.getMobile() + ", remark=" + this.getRemark() + ", sjid=" + this.getSjid() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", answerEntityList=" + this.getAnswerEntityList() + ", questionList=" + this.getQuestionList() + ")";
    }
}